import {
  formatTimestamp,
  groupByCluster,
  loadReport,
  overallStatus,
  statusLabel,
} from "./utils";
import { StatusBadge } from "./components/StatusBadge";
import { SummaryGrid } from "./components/SummaryGrid";
import { ServiceCard } from "./components/ServiceCard";

export default function App() {
  const report = loadReport();
  const clusters = groupByCluster(report.results);
  const overall = overallStatus(report);

  return (
    <div className="page">
      <div className="bg-glow bg-glow-a" />
      <div className="bg-glow bg-glow-b" />

      <main className="shell">
        <header className="hero">
          <div className="hero-top">
            <div>
              <p className="eyebrow">Amazon ECS Health Report</p>
              <h1>ECS Service Doctor</h1>
            </div>
            <StatusBadge status={overall} large label={statusLabel(overall)} />
          </div>

          <div className="hero-meta">
            <div className="meta-chip">
              <span className="meta-label">Generated</span>
              <span>{formatTimestamp(report.generated_at)}</span>
            </div>
            <div className="meta-chip">
              <span className="meta-label">Region</span>
              <span className="mono">{report.region}</span>
            </div>
            <div className="meta-chip">
              <span className="meta-label">Account</span>
              <span className="mono">
                {report.account_check.actual_account_id ?? "—"}
              </span>
            </div>
            <div className="meta-chip">
              <span className="meta-label">Version</span>
              <span className="mono">v{report.version}</span>
            </div>
          </div>

          {report.account_check.status === "FAIL" && (
            <div className="account-alert">{report.account_check.message}</div>
          )}
        </header>

        <SummaryGrid summary={report.summary} />

        {report.results.length === 0 ? (
          <section className="empty">No services were checked.</section>
        ) : (
          Array.from(clusters.entries()).map(([cluster, services]) => (
            <section key={cluster} className="cluster-panel">
              <div className="cluster-head">
                <h2>{cluster}</h2>
                <span>{services.length} service(s)</span>
              </div>
              <div className="service-grid">
                {services.map((service) => (
                  <ServiceCard key={`${cluster}-${service.service}`} item={service} />
                ))}
              </div>
            </section>
          ))
        )}

        <footer className="footer">
          Generated by {report.tool} · Self-contained report — no external assets
          required after export
        </footer>
      </main>
    </div>
  );
}
